apiVersion: v1
kind: Service
metadata:
  name: bucket-monitor-api
  namespace: object-monitor
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-port-443: |
      {
        "protocol": "https",
        "tls-secret-name": "api-tls-cert"
      }
spec:
  selector:
    app: bucket-monitor
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
