apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-nginx-conf
  namespace: monitoring
data:
  loki.conf: |
    resolver kube-dns.kube-system.svc.cluster.local;

    upstream identity_api {
        server token-auth-service.monitoring.svc.cluster.local:5000; # JWT auth service
    }

    server {
        root /var/www/html;
        listen 443 ssl; 
        listen [::]:443;
        index index.html index.htm index.nginx-debian.html;
        server_name logging.watch-folder.com; 
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        # Handle all Loki paths
        location / {
            rewrite ^ /_identity/protected$request_uri last;
        }

        location /auth {
            proxy_pass http://token-auth-service.monitoring.svc.cluster.local:5000/aka_restapi/api/auth;
            proxy_set_header Content-Type application/json;
        }

        # Single protected location block for Loki
        location ~ ^/_identity/protected(.*)$ {
            internal;
            auth_request /_oauth2_token_validation;
            proxy_pass http://loki.monitoring.svc.cluster.local:3100$1;  # Loki internal  service
            
            proxy_http_version 1.1;

            # These headers are important for Loki
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Original-URI $request_uri;
            
            # Increase timeouts for long-running Loki queries
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
            
            # Handle streaming responses
            proxy_set_header Connection "";
            
            # Increase buffer size for larger responses
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            
            error_log /var/log/nginx/error.log debug;
        }

        location = /_oauth2_token_validation {
            internal;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_pass http://token-auth-service.monitoring.svc.cluster.local:5000/aka_restapi/api/protected_route;
            proxy_set_header Authorization $http_authorization;
        }
    }
