apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      initContainers:
        - name: create-dummy-log
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Creating dummy log file for Promtail to tail"
              mkdir -p /run/promtail
              echo "Test log entry at $(date)" > /run/promtail/dummy.log
              echo "Dummy log created successfully"
          volumeMounts:
            - name: run
              mountPath: /run/promtail
      containers:
        - name: promtail
          image: grafana/promtail:2.8.2
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/config.yaml"
            - "-config.expand-env=true"
            - "-log.level=debug"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: run
              mountPath: /run/promtail
          ports:
            - name: http-metrics
              containerPort: 3101
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsUser: 0
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: run
          emptyDir: {}
