apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  config.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      # Directly scrape logs from application pods through sidecars
      - job_name: application-logs
        static_configs:
        - targets:
            - localhost
          labels:
            job: applogs
            __path__: /logs/*.log
            
      # Scrape a test log file we'll create to satisfy readiness
      - job_name: dummy-logs
        static_configs:
        - targets:
            - localhost
          labels:
            job: dummy
            __path__: /run/promtail/dummy.log
