apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: object-monitor
data:
  redis.conf: |
    maxmemory 6gb
    maxmemory-policy allkeys-lru
    appendonly yes
    protected-mode no
    tcp-keepalive 60
    timeout 300
    io-threads 4
    
  sentinel.conf: |
    port 26379
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1
    protected-mode no
