apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: object-monitor
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: object-monitor
  labels:
    app: redis
spec:
  ports:
  - port: 26379
    name: sentinel
  selector:
    app: redis
